// Aetrex internal onboarding content. Pure data, no React/JSX.

export const PHASES = [
  { id: "install",   name: "Install",   icon: "📥", description: "Open the app, connect the AI engine, sync the catalog." },
  { id: "configure", name: "Configure", icon: "⚙️", description: "Map attributes, upload Aetrex knowledge files." },
  { id: "integrate", name: "Integrate", icon: "🔌", description: "Wire in Yotpo, Aftership, Klaviyo, and the fit predictor." },
  { id: "launch",    name: "Launch",    icon: "🚀", description: "Style the widget, add to theme, QA, and monitor." },
  { id: "maintain",  name: "Maintain",  icon: "🔧", description: "Recurring tasks to keep the assistant healthy after launch." },
];

export const ATTRIBUTE_MAPPINGS = [
  { source: "metafield: custom.attr_gender",    attribute: "gender",     note: "Used to scope all category buttons + searches by men's / women's" },
  { source: "metafield: custom.attr_category",  attribute: "category",   note: "Sneakers, Sandals, Clogs, Loafers, Slippers, Oxfords, etc." },
  { source: "metafield: custom.attr_arch_type", attribute: "arch_type",  note: "Low / Medium / High — feeds fit recommendations" },
  { source: "metafield: custom.attr_fit_type",  attribute: "fit_type",   note: "Standard / Wide / Narrow — feeds size predictor" },
  { source: "metafield: custom.attr_use_case",  attribute: "use_case",   note: "Walking / Running / Casual / Dress / Athletic" },
  { source: "tag prefix: color:",               attribute: "color",      note: "Tags like 'color:black' map to the color attribute" },
  { source: "tag prefix: occasion:",            attribute: "occasion",   note: "Optional — only on dress styles" },
];

export const STEPS = [
  {
    phase: "install",
    icon: "📂",
    title: "Confirm install + open the app",
    short: "Apps → SEoS Assistant in the Aetrex Shopify admin.",
    body: "Open the SEoS Assistant app from the Aetrex Shopify admin (Apps → SEoS Assistant). The home page is the setup checklist — every following step lives in the admin, no external tools.",
  },
  {
    phase: "install",
    icon: "🔑",
    title: "Connect the AI engine",
    short: "Paste the Aetrex Anthropic key. Use Smart routing.",
    body: "Settings → AI engine → API key. Paste the Aetrex Anthropic API key (kept in 1Password under 'Anthropic — Aetrex prod'). Choose Smart routing as the strategy.",
    tip: "Smart routing sends 'thanks'/'ok' follow-ups to Claude Haiku and full product questions to Claude Sonnet, cutting cost on chatty conversations without affecting answer quality.",
  },
  {
    phase: "install",
    icon: "⏱",
    title: "Wait for the catalog to sync",
    short: "Aetrex's ~700 products mirror in 2–5 minutes.",
    body: "First load triggers a full Shopify catalog sync. Aetrex's catalog (~700 products) usually takes 2–5 minutes. The home page shows '[X] products synced' once it's done; do not move on until that number stabilizes.",
  },
  {
    phase: "configure",
    icon: "🗂",
    title: "Configure attribute mappings",
    short: "Map custom.attr_* metafields to clean attribute names.",
    body: "Rules & Knowledge → Catalog & attributes. Aetrex products use Shopify metafields under the `custom` namespace. Map each one to a clean attribute name the assistant uses for filtering. Use the reference table below — copy these exactly.",
    showAttributeTable: true,
  },
  {
    phase: "configure",
    icon: "📚",
    title: "Upload Aetrex knowledge files",
    short: "FAQs, brand voice, sizing, fit glossary, product attrs CSV.",
    body: "Rules & Knowledge → Knowledge files. Upload these files (kept in the shared Drive folder /Aetrex/SEoS-knowledge/):",
    list: [
      "aetrex-faqs.md — FAQ list (sizing, returns, shipping, technology questions)",
      "brand-voice.md — tone guidelines (warm, expert, never pushy)",
      "sizing-guide.md — Aetrex sizing chart and how to read it for men's/women's",
      "fit-glossary.md — definitions of Lynco, HealthySteps, arch types, fit types",
      "product-attributes.csv — SKU-keyed material/care/fit-notes per product",
    ],
    tip: "The CSV file with a SKU column auto-links to the catalog — useful for product-specific specs the AI can cite.",
  },
  {
    phase: "integrate",
    icon: "⭐",
    title: "Connect Yotpo (reviews + loyalty)",
    short: "Reviews powers fit summaries; Loyalty powers VIP perks.",
    body: "Settings → Integrations → Yotpo Reviews and Yotpo Loyalty & Referrals. Both keys live in 1Password under 'Yotpo — Aetrex'.",
    list: [
      "Yotpo Reviews API key → enables review-based fit summaries",
      "Yotpo Loyalty API key + GUID → enables points balance, tier, and personal referral link in chat",
    ],
  },
  {
    phase: "integrate",
    icon: "📦",
    title: "Connect Aftership",
    short: "Branded tracking + return-reason data for fit predictor.",
    body: "Settings → Integrations → Aftership. Paste the Aftership API key from 1Password. Two effects: return-reason data feeds the fit predictor (so 'too small' returns inform sizing recommendations), and tracking links shown to logged-in shoppers route to the Aetrex-branded Aftership tracking page.",
  },
  {
    phase: "integrate",
    icon: "📧",
    title: "Connect Klaviyo",
    short: "Segments adapt VIP-mode tone for logged-in shoppers.",
    body: "Settings → Integrations → Klaviyo. Paste the Aetrex Klaviyo Company ID, List ID, and private API key. The private key unlocks segment enrichment in VIP mode — the assistant adapts tone based on whether a logged-in shopper is in the VIP, Winback, or Churn Risk segments. Segment names are never shown to the customer.",
  },
  {
    phase: "integrate",
    icon: "👤",
    title: "Enable VIP mode",
    short: "Personalize chat for logged-in Aetrex customers.",
    body: "Settings → VIP customer experience → toggle VIP mode on. Logged-in shoppers now get personalized greetings, size recommendations anchored on their order history, and loyalty references in chat. None of their data is stored — every lookup is per-conversation, in-memory only.",
    tip: "Test VIP mode with a real Aetrex customer account that has at least 2 past orders. Without past orders the size predictor falls back to review and return data.",
  },
  {
    phase: "integrate",
    icon: "📏",
    title: "Configure the fit predictor",
    short: "Combines reviews + returns + history + Aetrex sizing API.",
    body: "Rules & Knowledge → Fit predictor → Enabled. The predictor combines Yotpo review fit data, Aftership return reasons, the customer's own order history, and the Aetrex external sizing API into a single confidence score per product. Paste the external sizing API endpoint and key from 1Password.",
  },
  {
    phase: "launch",
    icon: "🎨",
    title: "Customize the widget appearance",
    short: "Aetrex brand colors, logo, 'The Fit Concierge' naming.",
    body: "Open Theme Editor → SEoS Assistant block. Set the Aetrex brand colors (Primary #2D6B4F to match site, accent your existing CTA color), upload the Aetrex avatar (square logo), and set the welcome banner. Confirm the assistant name is 'The Fit Concierge' and the tagline matches the rest of the site.",
    tip: "The Enterprise plan removes the SEoS Assistant tagline from the widget footer. Confirm it's gone before going live.",
  },
  {
    phase: "launch",
    icon: "🧩",
    title: "Add the chat block to the live theme",
    short: "Add the block to the live theme body. Save.",
    body: "In Theme Editor, add the SEoS Assistant block to the body of the live Aetrex theme. Save. The launcher now appears in the bottom corner of every storefront page. If you want to hide it on specific pages (cart, checkout-confirmation), use Settings → Widget visibility → Hide-on URLs.",
  },
  {
    phase: "launch",
    icon: "✅",
    title: "QA with a real shopper account",
    short: "Verify VIP greeting, fit cards, loyalty, tracking, gender-first flow.",
    body: "Log into aetrex.com as a test customer with at least 2 past orders. Open the chat. Verify each:",
    list: [
      "Welcome message shows the customer's first name (VIP greeting)",
      "Asking 'what size should I get in [product]' returns a fit prediction card with a confidence percentage",
      "Asking about points or rewards mentions their actual Yotpo balance",
      "Asking about an order's tracking returns an Aftership link to the Aetrex-branded tracking page",
      "Asking 'I have foot pain, what should I wear?' walks the customer through gender → category → recommendation, only offering categories Aetrex actually sells for that gender",
    ],
  },
  {
    phase: "launch",
    icon: "📊",
    title: "Monitor in Analytics for the first week",
    short: "Watch satisfaction, AI cost, rate-limit hits.",
    body: "Analytics page tracks every conversation. Watch satisfaction rate (thumbs-up/down), AI cost, and rate-limit hits daily for the first week. Negative feedback surfaces specific responses to review and tune the knowledge files.",
    tip: "If AI cost spikes unexpectedly, set a Daily message cap in Settings → Daily message cap. The assistant pauses when the cap is hit and resumes the next day at midnight UTC.",
  },
  {
    phase: "maintain",
    icon: "🤖",
    title: "Update the AI model when Anthropic ships a new version",
    short: "Swap the model ID in Railway env vars — no code deploy needed.",
    body: "Model IDs (DEFAULT_MODEL, HAIKU_MODEL, OPUS_MODEL) are env-driven. When Anthropic releases a newer Claude (e.g. Sonnet 4.7, Opus 5.0), update the env var in Railway → Aetrex service → Variables → click the relevant variable → paste the new model ID → Save. The service auto-restarts in ~30 seconds.",
    list: [
      "DEFAULT_MODEL — the primary Sonnet model used for product questions and most chat",
      "HAIKU_MODEL — the cheap fast model used for trivial follow-ups when Smart routing is on",
      "OPUS_MODEL — used only when the routing strategy is 'always-opus' in admin",
    ],
    tip: "Always smoke-test 3–5 chats after switching models. If anything regresses (different phrasing, missed rules, wrong tool calls), revert the env var to the previous ID — instant rollback. Anthropic recommends explicit version pinning over 'latest' aliases.",
  },
  {
    phase: "maintain",
    icon: "⚠️",
    title: "Watch Railway logs for model deprecation warnings",
    short: "Anthropic gives ~6 months notice before a model retires.",
    body: "When a Claude model is deprecated, Railway logs print a warning on every chat call: 'The model X is deprecated and will reach end-of-life on [date]'. Anthropic gives roughly 6 months notice. When you see the warning, plan the model update task above before the EOL date — otherwise chat will start failing on that date.",
    tip: "Check the Anthropic model deprecation schedule monthly: https://docs.anthropic.com/en/docs/about-claude/model-deprecations",
  },
  {
    phase: "maintain",
    icon: "🧠",
    title: "Re-embed the catalog after big content edits",
    short: "Click Backfill in Rules & Knowledge after bulk product description changes.",
    body: "Individual product create/update webhooks auto-re-embed in the background. But bulk operations (CSV import, mass title rename, bulk description rewrite via a third-party tool) often skip webhooks. After such an operation, open Rules & Knowledge → Semantic search and click Backfill to refresh embeddings for any products that changed.",
    tip: "If the embedded count drops below the total products count and you didn't expect it, that's the sign — click Backfill until the bar hits 100% again.",
  },
  {
    phase: "maintain",
    icon: "📚",
    title: "Quarterly knowledge file review",
    short: "Keep aetrex-faqs / sizing-guide / fit-glossary current.",
    body: "Once per quarter, open Rules & Knowledge → Knowledge files and re-upload any of these that have changed on aetrex.com:",
    list: [
      "aetrex-faqs.md — if shipping policy, return policy, or FAQ page on the site changed",
      "sizing-guide.md — if Aetrex updated the sizing chart or added new size ranges",
      "fit-glossary.md — if a new technology line launches (Lynco, HealthySteps, etc.)",
      "product-attributes.csv — if you added new SKU-specific spec data",
    ],
    tip: "Outdated knowledge files = outdated AI answers. The AI will confidently quote stale return policies if the file says 30 days but the site says 60.",
  },
  {
    phase: "maintain",
    icon: "💳",
    title: "Monitor Anthropic credits & low-balance alerts",
    short: "Pay-as-you-go — chat goes silent if the balance hits zero.",
    body: "The Anthropic API key is pay-as-you-go from the merchant's (Aetrex's) credit balance at console.anthropic.com. If the balance reaches zero, every chat request fails with 'insufficient credit balance' and customers see the error fallback. Top up monthly or set up auto-recharge in Anthropic billing settings.",
    tip: "Configure low-balance email alerts in Anthropic console → Settings → Billing → Notifications. Set the threshold to ~30 days of typical spend to catch issues before they hit customers.",
  },
  {
    phase: "maintain",
    icon: "👍",
    title: "Review chat feedback weekly",
    short: "Analytics → Negative feedback list. Each thumbs-down is a tuning signal.",
    body: "Open Analytics every Monday. Scroll to the negative feedback section — each thumbs-down attaches the conversation that triggered it. Common patterns and their fixes:",
    list: [
      "Wrong product recommended → tune knowledge files or attribute mappings",
      "AI re-asked something already answered → check that conversation history is being passed correctly",
      "AI claimed a product doesn't exist when it does → check Search Rules / Category Groups for over-aggressive filtering",
      "AI gave outdated info → refresh the relevant knowledge file",
    ],
  },
  {
    phase: "maintain",
    icon: "🗂",
    title: "Keep Category Groups aligned with new product types",
    short: "Add new categories to the right group when Aetrex launches new lines.",
    body: "When Aetrex adds a new product type to Shopify (e.g. a new 'Sneaker Pro' category), open Rules & Knowledge → Category groups and add the new category to the right group (Footwear / Orthotics / Accessories). Without an entry, the new category falls outside the group filter and may appear in the wrong intent's chip list.",
    tip: "The Category Groups card in Rules & Knowledge shows your current groups. Compare against the catalog every time a new product line launches.",
  },

  // ── Quality testing system ────────────────────────────────────────
  {
    phase: "maintain",
    icon: "🧪",
    title: "How chat quality is measured",
    short: "Three layers of automated checks plus a real-customer feedback loop.",
    body: "The chat is protected by four layers of testing. Each one catches a different kind of bug before customers see it. You don't need to memorize how they work — when something feels off, run the relevant command, read the output, and fix or open a ticket.",
    list: [
      "Quick automated checks (eval) — 116 instant tests on the chat's logic. Free, takes 2 seconds. Run after any code change.",
      "Real-AI scenario tests (eval:scenarios) — simulated customer conversations sent to the real Anthropic API. Costs a few cents. Pass-rate tells you how the AI is actually behaving.",
      "Customer feedback loop (feedback:import) — every time a real customer hits 👎 in the chat widget, that conversation is stored. The import script pulls those into the test suite so the same bug never ships twice.",
      "Hallucination audit (audit:hallucinations) — scans recent live responses, extracts every product code and brand-line claim the AI made, and checks each one against your synced catalog. Surfaces the 'made-up SKU' and 'fake product line' bugs that pattern-based runtime guards can't catch alone.",
    ],
    tip: "Think of it as: 'quick checks' before deploy, 'AI scenarios' to measure quality, 'feedback' to learn from real customers, 'audit' to catch fabricated facts. All four commands live in the project — anyone with terminal access can run them.",
  },
  {
    phase: "maintain",
    icon: "✅",
    title: "Run the quick automated checks",
    short: "npm run eval — 91 instant tests, no API key needed.",
    body: "These are the fastest checks. They cover the chat's parsing, filtering, intent detection, banned-language stripping, and card-rendering logic. Free to run, finishes in 2 seconds. Run this before pushing any code change to main.",
    commands: [
      "git pull",
      "npm run eval",
    ],
    list: [
      "Output 'category-intent eval passed: 39/39' / 'choice-memory eval passed: 9/9' / 'chat-quality eval passed: 43/43' = ALL GOOD, safe to push.",
      "Any number on the left less than the number on the right = something broke. Don't deploy. Fix or revert.",
    ],
    tip: "If you're only changing rules/FAQ/brand text in the admin (not code), you don't need to run this — it tests code, not knowledge files. Skip to the AI scenario tests below.",
  },
  {
    phase: "maintain",
    icon: "🤖",
    title: "Run the real-AI scenario tests",
    short: "npm run eval:scenarios — 55 customer conversations vs the real AI.",
    body: "This is the dashboard for chat quality. It sends 55 representative customer questions to the real Anthropic API using the same system prompt the live chat uses, and checks whether the responses pass each scenario's assertions (no banned phrases, mentions the right product line, doesn't ask gender twice, etc.). Costs roughly $0.05–0.20 per run depending on the model.",
    commands: [
      "export ANTHROPIC_API_KEY=<your-key>",
      "npm run eval:scenarios",
    ],
    list: [
      "Pass rate ≥ 90% = healthy.",
      "Pass rate < 90% = something regressed. Each failed line shows the AI's actual response so you can see what broke.",
      "Re-run the same command 2–3 times and average — the AI is non-deterministic, expect ±2-3% variance per run.",
    ],
    tip: "The Anthropic API key lives in 1Password under 'Anthropic — Aetrex prod'. Set it once per terminal session with the export command, then run as many times as you like. Never paste it into a chat or commit it to git.",
  },
  {
    phase: "maintain",
    icon: "👎",
    title: "Pull customer thumbs-down into the test suite",
    short: "Every 👎 in the widget becomes a regression test.",
    body: "Whenever a customer hits the 'Not helpful' button in the chat widget, the conversation gets saved to the database. Run the feedback importer monthly (or after any complaint spike) to convert those into scenarios. The next test run will check whether the same kind of failure can still happen.",
    commands: [
      "npm run feedback:import",
      "npm run eval:feedback",
    ],
    list: [
      "feedback:import — reads the last 30 days of 👎 from the database and writes them to scripts/scenarios.from-feedback.json. Output tells you how many were imported. Each scenario now includes _source.detectedGender (auto-pulled from the conversation) so the eval triggers production gender-locking correctly.",
      "eval:feedback — runs those imported scenarios against the live AI. Prints WHEN RATED 👎 (what got the thumbs-down) vs RESPONSE NOW (what the AI says today) for each scenario, so you can compare side by side.",
      "IMPORTANT: '100% pass' on the feedback eval ONLY means the AI's responses don't contain banned phrases. It does NOT confirm the customer's actual concern is resolved. You need to read both responses and judge whether RESPONSE NOW is genuinely better. If they look the same, the underlying bug isn't fixed.",
    ],
    tip: "Optional flags: '--days=7' for the last week, '--shop=foo.myshopify.com' for one shop only, '--vote=all' to include 👍 too, '--no-dedupe' to keep every 👎, '--min-trigger=0' to keep short triggers like 'ok' (default skips anything under 8 chars to filter noise). The script prints a summary with how many were fetched, captured with conversation, deduped, and short-trigger-skipped.",
  },
  {
    phase: "maintain",
    icon: "🕵️",
    title: "Audit AI claims against the catalog",
    short: "npm run audit:hallucinations — find made-up SKUs and fake product lines.",
    body: "This scans recent chat responses and pulls out every product code (SKU) and brand-line claim ('Lynco is our premium orthotic line') the AI mentioned. It then checks each one against your synced Shopify catalog. Anything that doesn't resolve to a real product or variant gets flagged as a likely hallucination. Useful right before a demo, after a model upgrade, or whenever a stakeholder reports the AI 'made something up'. Read-only — never touches the live chat.",
    commands: [
      "npm run audit:hallucinations -- --days=30",
    ],
    list: [
      "Output prints a console summary (scanned / flagged / rate / top 10 flagged responses) plus a full JSON report at scripts/audit-hallucinations.json with every violation, the suspicious phrase, and a 400-char excerpt of what the AI said.",
      "Two violation kinds today: orphan-sku (the AI mentioned a SKU like L500 that isn't in any synced ProductVariant.sku for this shop) and definitional-claim (the AI said 'X is our premium line' but X isn't a known vendor or title token in the catalog).",
      "Flagged-rate of 0–2% is healthy; over 5% means either the catalog is out of sync (run a re-sync from Rules & Knowledge) or the model is genuinely fabricating — open the JSON report and look at the excerpts to tell which.",
    ],
    tip: "Optional flags: '--shop=foo.myshopify.com' for one shop, '--days=7' for last week, '--limit=200' to cap the scan, '--vote=down' to only audit thumbs-downed responses (those are the most suspicious already), '--json' to print the full report to stdout instead of the summary. Run this against production data — it reads ChatFeedback rows so it only sees responses that customers rated, which is the data set you most care about.",
  },
  {
    phase: "maintain",
    icon: "✏️",
    title: "Add a new scenario when you spot a bug",
    short: "Open scripts/scenarios.json, copy an example, change a few fields.",
    body: "When a customer or QA finds a chat issue that wasn't already covered, lock it in as a permanent test so it can't regress. The scenario file is plain JSON — you don't need to know JavaScript. Find a similar existing scenario, copy its block, edit the customer messages and what the AI must (or must not) say.",
    list: [
      "Each scenario has a name, optional 'history' array (prior turns), 'messages' array (the new user message(s)), and 'expect' object with assertions.",
      "Common assertions: mustContain (these phrases must appear), mustNotContain (these phrases must NOT appear), shouldMentionAny (at least one of these), shouldAskAbout (the AI should ask about one of these topics), maxSentences (response can't be longer than N).",
      "After editing the file, run 'npm run eval:scenarios' to confirm it passes (or fails as expected on a buggy build), then commit and push. The new scenario protects against that bug forever.",
    ],
    tip: "Don't write scenarios from scratch — open scripts/scenarios.json and copy the closest existing one. The 'no meta-narration' and 'soccer player asks for orthotic for cleats' scenarios are good templates for product flows; the 'asks about return policy' style is good for FAQ-style questions.",
  },
];
