ALTER TABLE "ShopConfig" ADD COLUMN IF NOT EXISTS "klaviyoFormId" TEXT NOT NULL DEFAULT '';
ALTER TABLE "ShopConfig" ADD COLUMN IF NOT EXISTS "klaviyoCompanyId" TEXT NOT NULL DEFAULT '';
ALTER TABLE "ShopConfig" ADD COLUMN IF NOT EXISTS "klaviyoListId" TEXT NOT NULL DEFAULT '';
