ALTER TABLE "ShopConfig" ADD COLUMN "rateLimitHits" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "ShopConfig" ADD COLUMN "rateLimitHitsMonth" TEXT NOT NULL DEFAULT '';
ALTER TABLE "CatalogSyncState" ADD COLUMN "syncedSoFar" INTEGER NOT NULL DEFAULT 0;
